# https://spacelift.io/blog/kubernetes-ingress
# Ingress Routing Roule
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: route-to-nginx-websrv
  namespace: dev-cgi-ac-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - maikslab.de
      secretName: maikslab-tls-secret
  ingressClassName: nginx
  rules:
    - host: maikslab.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-websrv
                port:
                  number: 80
