name: Azure Deployment # Workflow Name / Workflow Name

on: # Manuell start for Workflow on GibHub Action WebUi / Mit dieser Option startet der Workflow nur manuell über die GitHub Oberfläche
  workflow_dispatch:

# on: # Starts Workflow on every Push / Startet den Workflow bei jedem Push
#   push:
#     branches:
#       - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Image to use / Verwendetes Image
    
    env: # Access credentials for Microsoft Azure / Zugangsadaten für Microsoft Azure
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Terraform, Kubectl and Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

        wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

        gpg --no-default-keyring \
        --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
        --fingerprint
        
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list

        sudo apt update

        sudo apt-get install terraform

        terraform init

        sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

        kubectl version --client

    - name: Login to Azure
      run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

    - name: Your Deployment Steps
      run: |
        terraform apply -auto-approve
